version: '3.8'

services:
  python_admin:
    build:
      context: ./python_admin
      dockerfile: Dockerfile
    container_name: therapulse_python_admin
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - ENVIRONMENT=production
    restart: unless-stopped
